version: "3.9"
services: 
    api-service:
        build: .
        volumes: 
            - ./src/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1